staging: qcacld-3.0: Fix function prototype and array parameter warnings
- Fixed build errors related to missing function prototypes:
  - Added 'void' as the parameter for functions without arguments to comply with C standards.
  - Affected functions:
    - `target_if_get_ctx()`
    - `ce_services_srng()`

Fixes:
/home/securebyte/stx/kernel/msm-5.4/drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:98:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void

/home/securebyte/stx/kernel/msm-5.4/drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_srng.c:1014:32: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_srng()
                               ^
                                void

/home/securebyte/stx/kernel/msm-5.4/drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:6177:14: error: argument 'mdie' of type 'uint8_t[3]' (aka 'unsigned char[3]') with mismatched bound [-Werror,-Warray-parameter]
                   uint8_t mdie[SIR_MDIE_SIZE])
                           ^

Change-Id: Ic8dbaed6bedc68225b549ba35dbcc5de5f3721b2
Signed-off-by: 0xSecureByte <chirantan.code@gmail.com>