techpack: display: Fix uninitialized variable warnings
techpack/display/msm/sde/sde_connector.c:172:6: error: variable
'dsi_display' is used uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
        if (c_conn->connector_type == DRM_MODE_CONNECTOR_DSI) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
techpack/display/msm/sde/sde_connector.c:191:2: note: uninitialized use
occurs here
        dsi_display->panel->bl_config.oplus_raw_bl = brightness;
        ^~~~~~~~~~~
techpack/display/msm/sde/sde_connector.c:389:13: error: variable
'dsi_bl_config' is used uninitialized whenever 'if' condition is true
[-Werror,-Wsometimes-uninitialized]
        } else if (c_conn->connector_type == DRM_MODE_CONNECTOR_eDP) {
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
techpack/display/msm/sde/sde_connector.c:411:21: note: uninitialized use
occurs here
        props.brightness = dsi_bl_config->brightness_default_level;
                           ^~~~~~~~~~~~~
techpack/display/msm/sde/sde_connector.c:977:8: error: variable 'bd' is
used uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
                        if (!c_conn->allow_bl_update) {
                            ^~~~~~~~~~~~~~~~~~~~~~~~
techpack/display/msm/sde/sde_connector.c:994:16: note: uninitialized use
occurs here
        mutex_unlock(&bd->update_lock);
                      ^~
techpack/display/msm/sde/sde_connector.c:975:7: error: variable 'bd' is
used uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
                if (dp_panel) {
                    ^~~~~~~~
techpack/display/msm/sde/sde_connector.c:994:16: note: uninitialized use
occurs here
        mutex_unlock(&bd->update_lock);
                      ^~
techpack/display/msm/sde/sde_connector.c:972:13: error: variable 'bd' is
used uninitialized whenever 'if' condition is false
[-Werror,-Wsometimes-uninitialized]
        } else if (c_conn->connector_type == DRM_MODE_CONNECTOR_eDP) {
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
techpack/display/msm/sde/sde_connector.c:994:16: note: uninitialized use
occurs here
        mutex_unlock(&bd->update_lock);
                      ^~
5 errors generated.

Change-Id: I9944baf14c55885a0ce62425c576fba945050674